module.exports = {
    tags: {
        'action': 'action-26',
        'adult': 'adult-68',
        'adventure': 'adventure-27',
        'anime': 'anime-62',
        'chuyển sinh': 'chuyen-sinh-91',
        'cổ đại': 'co-dai-90',
        'comedy': 'comedy-28',
        'comic': 'comic-60',
        'demons': 'demons-99',
        'detective': 'detective-100',
        'doujinshi': 'doujinshi-96',
        'drama': 'drama-29',
        'đam mỹ': 'dam-my-93',
        'ecchi': 'ecchi-50',
        'fantasy': 'fantasy-30',
        'gender bender': 'gender-bender-45',
        'harem': 'harem-47',
        'historical': 'historical-51',
        'horror': 'horror-44',
        'huyền huyễn': 'huyen-huyen-468',
        'isekai': 'isekai-85',
        'josei': 'josei-54',
        'mafia': 'mafia-69',
        'magic': 'magic-58',
        'manhua': 'manhua-35',
        'manhwa': 'manhwa-49',
        'martial arts': 'martial-arts-41',
        'mature': 'mature-48',
        'military': 'military-101',
        'mystery': 'mystery-39',
        'ngôn tình': 'ngon-tinh-87',
        'one shot': 'one-shot-95',
        'psychological': 'psychological-40',
        'romance': 'romance-36',
        'school life': 'school-life-37',
        'sci-fi': 'sci-fi-43',
        'seinen': 'seinen-42',
        'shoujo': 'shoujo-38',
        'shoujo-ai': 'shoujo-ai-98',
        'shounen': 'shounen-31',
        'shounen-ai': 'shounen-ai-86',
        'slice of life': 'slice-of-life-46',
        'smut': 'smut-97',
        'sports': 'sports-57',
        'supernatural': 'supernatural-32',
        'tragedy': 'tragedy-52',
        'trọng sinh': 'trong-sinh-82',
        'truyện màu': 'truyen-mau-92',
        'webtoon': 'webtoon-55',
        'xuyên không': 'xuyen-khong-88',
        'yaoi': 'yaoi-70',
        'yuri': 'yuri-75'
    },
    status: {
        'đang tiến hành': 0,
        'hoàn thành': 2
    },
    country: {
        'china': 1,
        'vietnam': 2,
        'korea': 3,
        'japan': 4,
        'america': 5,
    },
    sort: {
        'ngày đăng giảm dần': 0,
        'ngày đăng tăng dần': 1,
        'ngày cập nhật giảm dần': 2,
        'ngày cập nhật tăng dần': 3,
        'lượt xem giảm dần': 4,
        'lượt xem tăng dần': 5
    },
    keyID: ['truyen-moi-cap-nhat', 'truyen-con-gai', 'truyen-con-trai',
        'top-ngay', 'top-tuan', 'top-thang', 'truyen-yeu-thich', 'truyen-tranh-moi',
        'truyen-hoan-thanh', 'truyen-ngau-nhien']
}